**Carl Stermann-Lücke**

## Session 2: Working with Data using NumPy & Pandas
* NumPy arrays: creation, indexing, operations
* Pandas DataFrames: loading, filtering, describing data
* Real dataset mini-example (e.g., Iris or simple CSV)

# Numpy

Numpy is a library that provides data structures for vectors, matrices and tensors, and functions for performing computations on these data structures. These data structures are collectively called "Numpy Arrays".
In machine learning, we often deal with many numbers that are structured with indices, that means, as a tensor.
As you have learned before, python also provides lists. You could think that you could build arrays out of lists. But numpy arrays are optimized to allow easy access to specific elements and parts of the array, to perform operations on every element, and to do so much faster than we could do with lists.

The official website of numpy: https://numpy.org

Since numpy is a library, you need to import it. Every python installation includes numpy, so you don't need to install it separately.
The convention is to import numpy as np, like so:

In [2]:
import numpy as np
# Run this cell before anything else

## Numpy Arrays

We can make a numpy array of arbitrary numbers:

In [2]:
np.array([3,2,1,0])

array([3, 2, 1, 0])

The above Numpy Array has one dimension. That means, every number in the array has a position in the array that can be identified with exactly one number. For example, the first number in the array has the index 0.

In [3]:
myArray = np.array([3,2,1,0])
myArray[0]

3

Numpy Arrays can have more than one dimension. Think of it as a matrix or a tensor.

In [4]:
# 2 dimensional numpy array
my2dArray = np.array([[3,2],[1,0]])

my2dArray

array([[3, 2],
       [1, 0]])

In [5]:
# 3 dimensional numpy array
my3dArray = np.array([[[7,6],[5,4]],[[3,2],[1,0]]])

my3dArray

array([[[7, 6],
        [5, 4]],

       [[3, 2],
        [1, 0]]])

Not that this is nothing but a list (of lists) passed into the np.array function. So you can also make a list first and then pass it:

In [41]:
myList = [[[7,6],[5,4]],[[3,2],[1,0]]]
my3dArray = np.array(myList)
my3dArray

array([[[7, 6],
        [5, 4]],

       [[3, 2],
        [1, 0]]])

You can access the individual elements by providing more than one index:

In [6]:
print(my2dArray[0,1])
print(my3dArray[0,1,1])

2
4


Now let's compare operations on lists vs numpy arrays:

In [7]:
list1 = [1,2,3,4]
list2 = [1,2,3,4]
list3 = [[1,2,3,4],[1,2,3,4]]

In [8]:
list1 + list2

[1, 2, 3, 4, 1, 2, 3, 4]

In [9]:
list3 + list1

[[1, 2, 3, 4], [1, 2, 3, 4], 1, 2, 3, 4]

In [10]:
list1 * list2

TypeError: can't multiply sequence by non-int of type 'list'

Since multiplication is not defined on lists, you see an error here. Not so with numpy arrays...

In [11]:
numpyarray1 = np.array([1,2,3,4])
numpyarray2 = np.array([1,2,3,4])
numpyarray3 = np.array([[1,2,3,4],[1,2,3,4]])

In [12]:
numpyarray1 + numpyarray2

array([2, 4, 6, 8])

In [13]:
numpyarray3 + numpyarray1

array([[2, 4, 6, 8],
       [2, 4, 6, 8]])

In [14]:
numpyarray1 * numpyarray2

array([ 1,  4,  9, 16])

In [15]:
numpyarray3 * numpyarray1

array([[ 1,  4,  9, 16],
       [ 1,  4,  9, 16]])

Elements in the numpy array can be any types. However, if the types are different from one another, then one type would be the type of the array we set; that means all the elements are converted to the same type. Python decides which type that will be. For instance, if you use a mix of integers and strings, the string would be the final type of all elements. Also note that when you initially decide on which type you want to create your array, and later you if you insert an element within the array with different type, the type of the new element would be converted to the original type of the array, if possible. Look at the following examples.

In [16]:
x1 = np.array([1,2,3,4])
x2 = np.array([1,2,3,"C"])
print(type(x1[0]), type(x2[0]))

<class 'numpy.int32'> <class 'numpy.str_'>


x1 is an array of integers.
x2 is an array of strings.
Now what happens if we replace the only "actual" string in x2 by an integer?

In [17]:
x2[3] = 4
print(x2)
print(type(x2[3]))

['1' '2' '3' '4']
<class 'numpy.str_'>


You see that, even though we have changed the last element of x2 to an integer, the type still remains string.

Any what happens if we include a non-integer (float) in the integer array x1?

In [18]:
x1[3] = 7.7
print(x1)
print(type(x1[3]))

[1 2 3 7]
<class 'numpy.int32'>


You see that the type of the element at position 3 of x1 is still integer, even though we have put a float number there.

Does that also work with strings?

In [19]:
x1[3] = "C"
print(x1)
print(type(x1[3]))

ValueError: invalid literal for int() with base 10: 'C'

Strings cannot be converted to integer, so we cannot put a string into an integer array.

A side note: If you insert integers, strings, and booleans in a numpy array, you get to have a single type of string.
Note that the property of the NumPy array which requires it to hold elements of a single type makes the NumPy faster in calculation compared with list. Also note that if you have a numpy array with booleans and number types (float, integer), numpy will convert the boolean `True` to 1 and `False` to 0.

For our purposes, it only makes sense to have numpy arrays of integers, floats or booleans.

## Slicing: Accessing specific elements from a numpy array

Slicing means accessing a subsection of a numpy array.
The following examples can represent how it works.

Let's experiment with a simple one-dimensional numpy array

In [21]:
simpleArray = np.array([19,8,7,1,5,4])

In [22]:
firstElement = simpleArray[0]
firstElement
# Numpy arrays start indexing with 0, just like lists.

In [23]:
lastElement = simpleArray[-1]
lastElement
# The second-to-last element would be simpleArray[-2].

In [24]:
withoutFirstAndLastElement = simpleArray[1:-1]
withoutFirstAndLastElement
# x:y means every element from position x (including) to position y (excluding). If x is not given, it takes elements from the start. If y is not given, it takes elements to the end.

How does that work with a two-dimensional numpy array?

In [25]:
myArray = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [26]:
firstRow = myArray[0,:]
firstRow

In [27]:
firstColumn=myArray[:,0]
firstColumn

In [28]:
secondColumn = myArray[:,1]
secondColumn

In [29]:
oddRowsEvenColumns = myArray[1::2,0::2]
oddRowsEvenColumns
# x:y:z means every element from x (including) to y (excluding) in steps of z. Like before, if x is not given, it takes elements from the start. If y is not given, it takes elements to the end.

## Shape and Reshape

You might want to change the dimensions of a numpy array. For this, you can use the shape and reshape functions.

In [30]:
myarray = np.array([[2,5,6],[3,4,7]])

In [31]:
myarray.shape
# this shows: (gives the number of rows and columns of myarray) the dimensionality and the size of each dimension.

(2, 3)

In [32]:
myarray.reshape(-1,1)
# The size of the new array in each dimension is given. If you type -1, that dimension is going to be computed based on the number of elements in the original array.

array([[2],
       [5],
       [6],
       [3],
       [4],
       [7]])

In [33]:
myarray.reshape(-1)
# It's also possible to change the dimensionality. This now is a one-dimensional array,

array([2, 5, 6, 3, 4, 7])

In [34]:
myarray.reshape(2,1,-1)
# The dimensionality can also be increased. Only one parameter can be -1, because otherwise it could not be inferred.
# the number of numbers inside parentheses determines the dimensionality of the array, the -1 will automatically provide the adequate number,
# and the multiplication of the numbers (excluding -1, means including any proper multiplication) should match to the numbers of the elements of the array.

array([[[2, 5, 6]],

       [[3, 4, 7]]])

## linspace

Linspace function is being used to create a line with the amount of discretization that we would like to have. For instance, if we want to have a 20 meters stick and we want to chop it 100 times, each piece would have 0.2 meter length, this can be useful in some problem. This example can be seen in the following code

In [35]:
np.linspace(0,20,100)

array([ 0.        ,  0.2020202 ,  0.4040404 ,  0.60606061,  0.80808081,
        1.01010101,  1.21212121,  1.41414141,  1.61616162,  1.81818182,
        2.02020202,  2.22222222,  2.42424242,  2.62626263,  2.82828283,
        3.03030303,  3.23232323,  3.43434343,  3.63636364,  3.83838384,
        4.04040404,  4.24242424,  4.44444444,  4.64646465,  4.84848485,
        5.05050505,  5.25252525,  5.45454545,  5.65656566,  5.85858586,
        6.06060606,  6.26262626,  6.46464646,  6.66666667,  6.86868687,
        7.07070707,  7.27272727,  7.47474747,  7.67676768,  7.87878788,
        8.08080808,  8.28282828,  8.48484848,  8.68686869,  8.88888889,
        9.09090909,  9.29292929,  9.49494949,  9.6969697 ,  9.8989899 ,
       10.1010101 , 10.3030303 , 10.50505051, 10.70707071, 10.90909091,
       11.11111111, 11.31313131, 11.51515152, 11.71717172, 11.91919192,
       12.12121212, 12.32323232, 12.52525253, 12.72727273, 12.92929293,
       13.13131313, 13.33333333, 13.53535354, 13.73737374, 13.93

## arange

Arange is a function that generate arrays with desired space between the elements. It is similar to linspace with the difference that the last number would indicate the size of the steps rather than the number of the steps. It works exactly like range, except that it makes numpy array. Look at the section about `range` The following examples would elaborate on it better.

In [39]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [40]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

### comparing arange and linspace

These two commands are often mixed up.

In [ ]:
np.linspace(4,20,3)

In [ ]:
np.arange(4,20,3)

The difference is that the last parameter (the 3 in the examples above) has different meaning.
For linspace, it indicates the number of substeps.
For arange, it indicates the step size between substeps.

## meshgrid

Meshgrid can help us find the coordinates of a certain point in a multi-dimensional space. It takes input arrays that can be seen as coordinate axes. Let’s assume we give two arrays. These form the coordinate axes of a two-dimensional space. Meshgrid tells us the coordinates for each position in the resulting two-dimensional array. Each position has (in the two-dimensional case) two coordinates. So meshgrid retuns two two-dimensional arrays, one with all the coordinates in the first and the other in the second dimension.

In [3]:
x =[1, 2, 3, 4]
y =[5, 6, 7]
np.meshgrid (x, y)

[array([[1, 2, 3, 4],
        [1, 2, 3, 4],
        [1, 2, 3, 4]]),
 array([[5, 5, 5, 5],
        [6, 6, 6, 6],
        [7, 7, 7, 7]])]

## random

Numpy can fill arrays with random numbers of different ranges and distributions. It is a good practice to use a random number generator object to generate random numbers. Such a random number generator can be provided with a fixed seed. That means, it will produce the same random numbers every time you run the program. This is useful for statistical comparisons between runs. For example, in machine learning, you might want to test your model by feeding it data in random order. If you want to compare your model with a baseline model, you want to feed the same data in and also in the same order. You will need fewer runs to tell with statistical significance which model performs better.

Let's first create two instances of random number generators to demonstrate this effect.

In [15]:
# This random number generator has no seed. Run this cell multiple times.
generator = np.random.default_rng()
generator.integers(low=0, high=10, size=3)

array([1, 0, 8], dtype=int64)

Now compare the output to this one:

In [20]:
# This random number generator has a seed number. Run this cell multiple times.
generator = np.random.default_rng(42)
generator.integers(low=0, high=10, size=3)

array([0, 7, 6], dtype=int64)

The seed determines the random numbers, but in a way that is intentionally hard for humans to understand and reverse-engineer. Check out what happens when we use a different seed:

In [24]:
# This random number generator has a different seed number than the one above. Run this cell multiple times.
generator = np.random.default_rng(12345)
generator.integers(low=0, high=10, size=3)

array([6, 2, 7], dtype=int64)

It's not actually true that the random number generator without the seed has no seed. It has a seed, but that is determined automatically and it's not always the same. Often, the seeds are determined by user input, the system clock, or other things that are hard to control exactly.

Another thing that is important to know about random number generators is that, once they are initialized with a seed, they will continue producing new (pseudo) random numbers. So they don't get used up. When you have a random number generator and you don't know how many numbers it has generated, the next number will appear random to you.
For example, when you run the following cell, it will very likely not output the same result as any of the previous three cells:

In [25]:
generator.integers(low=0, high=10, size=3)

array([3, 2, 7], dtype=int64)

Try to run it again multiple times. You will always get new numbers, as long as you keep using the same random number generator.
So it is best practice to set up the random number generator once at the beginning of each of your experiments, and then use it throughout the experiment.

Now that we have a random number generator (no matter which of the three you use), let's explore more options to fill numpy arrays with random numbers.

In [31]:
# A two-dimensional array with 2 x 3 random integers between 0 (inclusive) and 10 (exclusive)
generator.integers(low=0, high=10, size=(2,3))

array([[1, 7, 7],
       [2, 7, 0]], dtype=int64)

In [27]:
# A one-dimensional array with three random numbers between 0 and 1
generator.random(3)

array([0.67625467, 0.39110955, 0.33281393])

In [29]:
# A two-dimensional array with 2 x 3 random numbers between 0 and 1
generator.random((2,3))

array([[0.59830875, 0.18673419, 0.67275604],
       [0.94180287, 0.24824571, 0.94888115]])

In real life, not every random number is equally likely. Or, well, actually it is, but not every range of numbers is equally likely to have a random number generated in. So, let's create random numbers with normal distribution:

In [30]:
# A two-dimensional array with 2 x 3 random numbers that are normally (gaussian) distributed with mean of 0 and standard deviation of 1. The parameters for mean and standard deviation are called 'loc' and 'scale' in this function.
generator.normal(loc=0.0, scale=1.0, size=(2,3))

array([[-0.75938718,  0.90219827, -0.46695317],
       [-0.06068952,  0.78884434, -1.25666813]])

As you have certainly observed, the 'size' parameter can be a whole positive number. Then you get a one-dimensional array of the specified size. Or it can be a tuple of an arbitrary number of whole positive numbers. Then you get a multi-dimensional array where the sizes of each dimension is the number you specified in the tuple.

It can also be useful to randomly reorder the elements of a numpy array:

In [44]:
x = np.array([1,2,3,4,5])
generator.shuffle(x) # shuffle shuffles inplace, that means it does not create a new numpy array.
x

array([3, 1, 2, 5, 4])

In [45]:
xy = np.array([[1,2,3,4,5],[6,7,8,9,10]])
generator.shuffle(xy)
xy

array([[ 6,  7,  8,  9, 10],
       [ 1,  2,  3,  4,  5]])

You can also shuffle each row or column independently, or in bulk. Compare:

In [46]:
xy = np.array([[1,2,3,4,5],[6,7,8,9,10]])
generator.permuted(xy, axis=0) # permuted creates a new array and does not change the original one

array([[ 6,  7,  3,  9,  5],
       [ 1,  2,  8,  4, 10]])

In [47]:
generator.permuted(xy, axis=1)

array([[ 3,  1,  2,  5,  4],
       [ 8, 10,  7,  9,  6]])

In [52]:
# now in bulk
generator.permutation(xy, axis=0) # permutation creates a new array and does not change the original one
# you might need to try this several times to see what happens

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [53]:
generator.permutation(xy, axis=1)
# you see that here, the entire columns get reordered, not just individual numbers.

array([[ 1,  2,  4,  3,  5],
       [ 6,  7,  9,  8, 10]])

### Axis

You have seen the parameter 'axis' in the previous examples (permuted and permutation).
This parameter is used to tell which dimension of a numpy array you want to apply a function to.
Above you have seen that you can initialize a numpy array using a list, or a list of lists. axis = 0 refers to the outermost list. axis = 1 means the next level of lists. And so on.

## stacking

You have two arrays and want to append one to the other? hstack and vstack might be what you are searching for.

In [32]:
x = np.array([1,2,3])
y = np.array([4,5,6])
np.hstack((x,y))

array([1, 2, 3, 4, 5, 6])

hstack stacks horizontally, vstack stacks vertically

In [35]:
np.vstack((x,y))

array([[1, 2, 3],
       [4, 5, 6]])

Be careful, because dimensions need to match. Take the following two examples where they don't match:

In [36]:
z = np.array([[7],[8]])
np.hstack((x,z))

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 1 dimension(s) and the array at index 1 has 2 dimension(s)

In [37]:
z1 = np.array([11,12])
np.vstack((x,z1))

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 3 and the array at index 1 has size 2

## Conditional Selection

The following example will illustrate how we can select elements of a numpy array that meet a certain condition.

In [38]:
x = np.array([1, 7, 4, 90, 12.4, 56, 10, 2, 0, -5, 22, 34, 65, 10, -4, 17, 2])

In [39]:
x < 12

array([ True,  True,  True, False, False, False,  True,  True,  True,
        True, False, False, False,  True,  True, False,  True])

You now have an array of booleans. This you can use to filter an array (for example the original array, like here):

In [40]:
x[x<12]

array([ 1.,  7.,  4., 10.,  2.,  0., -5., 10., -4.,  2.])

Or from a different array:

In [42]:
list1 = ["Carl", "Hanna", "Piter", "Ali", "Hassan", "Paul", "Zainab", "Zahra", "Catalina", "Anna", "Julia", "Dina", "Sara", "Lina", "Albert"]
list2 = [1.80, 1.67, 1.87, 1.55, 1.77, 1.56, 1.78, 1.69, 1.80, 1.58, 1.87, 1.59, 1.65, 1.90, 1.79]
name_np = np.array(list1)
height_np = np.array(list2)
print ("Zahra height = ", height_np [ name_np =="Zahra"], "Julia height = ", height_np [ name_np =="Julia"])

 Zahra height =  [1.69] Julia height =  [1.87]


## np.where

This function can be used to apply an operation on particular elements of a numpy array. Here you find an example where it returns the absolute value of a list of numbers.

In [54]:
myArray = np.array([9, 1, 4, 2, -4, 1, -6, -1, 4])
np.where(myArray < 0, -myArray, myArray)

array([9, 1, 4, 2, 4, 1, 6, 1, 4])

## Statistical Methods

Here are some numpy functions that can be useful dealing with data. Functions like: mean, median, min, max, std.

In [55]:
student_heights = [1.80, 1.67, 1.87, 1.55, 1.77, 1.56, 1.78, 1.69, 1.80, 1.58, 1.87, 1.59, 1.65, 1.90, 1.79]
np_student_heights = np.array(student_heights)
np.mean(np_student_heights)

1.7246666666666666

In [56]:
np.median(np_student_heights)

1.77

In [57]:
np.max(np_student_heights)

1.9

In [58]:
np.min(np_student_heights)

1.55

In [59]:
np.std(np_student_heights)

0.11552008002459524

## Error with math versus numpy

We have seen that basic arithmetic operations, such as addition or multiplication, can be performed on numpy arrays and apply to every element. Some mathematical operations are implemented as functions in the math package, such as sqrt, sin, cos, etc. These do not work on numpy arrays, as you can try here:

In [60]:
import math
myarray = np.array([1,2,3])
# Trying to calculate the square root of every element in the array.
math.sqrt(myarray)

TypeError: only length-1 arrays can be converted to Python scalars

The solution is to use the functions from the numpy package, not from the math package:

In [61]:
import math
myarray = np.array([1,2,3])
# Trying to calculate the square root of every element in the array, but this time using the numpy function.
np.sqrt(myarray)

array([1.        , 1.41421356, 1.73205081])

## Efficiency of array operations

Numpy can apply operations to every element of an array, and it can do so a lot faster than we could do that with a simple loop. In the following example, we compute the first 1000000 Fibonacci-numbers (with a very nice formula) and measure the time to do this, both with a numpy array and with a for-loop.

In [64]:
import numpy as np
import time

array = np.arange (0 ,1000000 ,1) # every number from 0 to 999999

a = (1 + np.sqrt (5) ) / 2
b = (1 - np.sqrt (5) ) / 2
numpy_start = time.process_time()
fibonacciNumpy = (1 / np.sqrt (5)) * ((a ** array) - (b ** array))
numpy_stop = time.process_time()
fibonacciByHand = np.zeros (1000000)
hand_start = time.process_time()
for n in range (0, 1000000):
    fibonacciByHand [n] = (1/ np.sqrt (5)) * ((a ** n) - (b ** n))
hand_stop = time.process_time()
numpy_time = numpy_stop - numpy_start
hand_time = hand_stop - hand_start
print ("numpy_time", numpy_time )
print ("hand_time", hand_time )
# don't print the actual fibonacci numbers, they are too many

C:\Users\carl.stermann-luecke\AppData\Local\Temp\ipykernel_31796\628953967.py:9: RuntimeWarning: overflow encountered in power
  fibonacciNumpy = (1 / np.sqrt (5)) * ((a ** array) - (b ** array))
C:\Users\carl.stermann-luecke\AppData\Local\Temp\ipykernel_31796\628953967.py:14: RuntimeWarning: overflow encountered in scalar power
  fibonacciByHand [n] = (1/ np.sqrt (5)) * ((a ** n) - (b ** n))


numpy_time 0.421875
hand_time 7.265625


This is also a good example for how to measure time in python.